baseurl = "/"
languageCode = "en-uk"
title = "Field-Work-2018"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"

[params]
    description = "Grassland field work in 2018."

    [params.logo]
    url = "uav.png"
    width = 50
    height = 50
    alt = "Logo"

